{
 "title": "OpenStack Exporter Instance Abuse Monitoring",
 "tags": [
  "openstack",
  "openstack_instance_abuse"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "gvar_oie_hypervisor",
    "label": "Hypervisor",
    "query": {
     "query": "label_values(oie_cpu_percent, hypervisor)"
    }
   },
   { "name": "gvar_oie_project_uuid", "label": "Project UUID", "query": { "query": "label_values(project_uuid)" } },
   {
    "name": "gvar_oie_instance_uuid",
    "label": "Instance UUID",
    "query": {
     "query": "label_values({project_uuid=~\"$gvar_oie_project_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"},instance_uuid)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance CPU Usage",
   "type": "timeseries",
   "description": "Display CPU usage above 75% for more than 5 consecutive minutes.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(oie_cpu_percent{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[5m]) > 75",
     "legendFormat": "Instance {{ instance_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  { "title": "Disk Usage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Disk Write Requests (IOPS)",
   "type": "timeseries",
   "description": "Display disk write request IOPS above tier threshold. Thresholds are dynamic per tier. If it is on here, it is over its threshold!",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(oie_disk_w_requests{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[5m]) > oie_disk_w_alert_threshold\n",
     "legendFormat": "Instance {{ instance_uuid }} | Disk Type: {{ disk_type }}  | Disk Type: {{ disk_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Disk Read Requests (IOPS)",
   "type": "timeseries",
   "description": "Display disk read request IOPS above tier threshold. Thresholds are dynamic per tier. If it is on here, it is over its threshold!",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(oie_disk_r_requests{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[5m]) > oie_disk_r_alert_threshold\n",
     "legendFormat": "Instance {{ instance_uuid }} | Disk Type: {{ disk_type }}  | Disk Type: {{ disk_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Disk Write Throughput",
   "type": "timeseries",
   "description": "Display disk write throughput above 50MB/s for more than 5 consecutive minutes",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "targets": [
    {
     "expr": "min_over_time(rate(oie_disk_w_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[5m])[5m:]) > 0.05\n",
     "legendFormat": "Instance {{ instance_uuid }} | Disk Type: {{ disk_type }}  | Disk Type: {{ disk_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Disk Read Throughput",
   "type": "timeseries",
   "description": "Display disk read throughput above 50MB/s for more than 5 consecutive minutes",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "targets": [
    {
     "expr": "min_over_time(rate(oie_disk_r_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[5m])[5m:]) > 0.05\n",
     "legendFormat": "Instance {{ instance_uuid }} | Disk Type: {{ disk_type }}  | Disk Type: {{ disk_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Disk Write High Usage (GB)",
   "type": "timeseries",
   "description": "Display disk write high usage if greater than 20GB in a 30 minute span. Note that this is not cumulative, it only represents the period in which it was high.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(\n  increase(oie_disk_w_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[30m]) > 20\n) OR absent(increase(oie_disk_w_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[30m]))\n",
     "legendFormat": "Instance {{ instance_uuid }} | Disk Type: {{ disk_type }}  | Disk Type: {{ disk_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Disk Read High Usage (GB)",
   "type": "timeseries",
   "description": "Display disk read high usage if greater than 20GB in a 30 minute span. Note that this is not cumulative, it only represents the period in which it was high.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(\n  increase(oie_disk_r_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[30m]) > 20\n) OR absent(increase(oie_disk_r_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[30m]))\n",
     "legendFormat": "Instance {{ instance_uuid }} | Disk Type: {{ disk_type }}  | Disk Type: {{ disk_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  { "title": "Network Usage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Network RX Usage (GB)",
   "type": "timeseries",
   "description": "Display network receive usage in gigabytes if greater than 20GB in a 30 minute consecutive period.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(\n  increase(oie_net_rx_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[30m]) > 20\n) OR absent(count_over_time(oie_net_rx_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[30m]))\n",
     "legendFormat": "Instance {{ instance_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Network TX Usage (GB)",
   "type": "timeseries",
   "description": "Display network transmit usage in gigabytes if greater than 20GB in a 30 minute consecutive period.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(\n  increase(oie_net_tx_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[30m]) > 20\n) OR absent(count_over_time(oie_net_tx_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[30m]))\n",
     "legendFormat": "Instance {{ instance_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Network RX Throughput",
   "type": "timeseries",
   "description": "Display network receive throughput if greater than 125Mbit/s and transfer total is greater than 20 gigabytes in 30 consecutive minutes.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "targets": [
    {
     "expr": "(rate(oie_net_rx_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[5m]) / 8) > 0.125\nand \nincrease(oie_net_rx_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[30m]) > 20\n\n",
     "legendFormat": "Instance {{ instance_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Network TX Throughput",
   "type": "timeseries",
   "description": "Display network transmit throughput if greater than 125Mbit/s and transfer total is greater than 20 gigabytes in 30 consecutive minutes.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "targets": [
    {
     "expr": "(rate(oie_net_tx_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[5m]) / 8) > 0.125\nand \nincrease(oie_net_tx_gbytes{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\", hypervisor=~\"$gvar_oie_hypervisor\"}[30m]) > 20\n\n",
     "legendFormat": "Instance {{ instance_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Network RX Packets PPS",
   "type": "timeseries",
   "description": "Display network receive packets per second above 10000/pps if consecutive for more than 1 minute.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "min_over_time(rate(oie_net_rx_pkt_total{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\"}[5m])[1m:]) > 10000",
     "legendFormat": "Instance {{ instance_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Network TX Packets PPS",
   "type": "timeseries",
   "description": "Display network transmit packets per second above 10000/pps if consecutive for more than 1 minute.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "min_over_time(rate(oie_net_tx_pkt_total{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\"}[5m])[1m:]) > 10000",
     "legendFormat": "Instance {{ instance_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Network RX Dropped Packets",
   "type": "timeseries",
   "description": "Display network receive dropped packets if greater than 0.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(oie_net_rx_drp_total{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\"}[5m]) > 0",
     "legendFormat": "Instance {{ instance_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Network TX Dropped Packets",
   "type": "timeseries",
   "description": "Display network transmit dropped packets if greater than 0.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(oie_net_tx_drp_total{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\"}[5m]) > 0",
     "legendFormat": "Instance {{ instance_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Network RX Packet Errors",
   "type": "timeseries",
   "description": "Display network receive packet errors if greater than 0.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(oie_net_rx_er_total{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\"}[5m]) > 0",
     "legendFormat": "Instance {{ instance_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  },
  {
   "title": "Network TX Packet Errors",
   "type": "timeseries",
   "description": "Display network transmit packet errors if greater than 0.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(oie_net_tx_er_total{project_uuid=~\"$gvar_oie_project_uuid\", instance_uuid=~\"$gvar_oie_instance_uuid\"}[5m]) > 0",
     "legendFormat": "Instance {{ instance_uuid }} | Project: {{ project_uuid }} | Hypervisor: {{ hypervisor }}"
    }
   ]
  }
 ]
}